[package]
name = "exchange-binance"
version.workspace = true
edition.workspace = true

[dependencies]
domain = { path = "../domain" }
chrono.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
hmac.workspace = true
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true
